export const CURRENT_STATUS_GLOW_CONFIG = {
  maxLength: 42,
  maxOpacity: 1,
  travelDuration: 2,
  fadeInDuration: 0.9,
  fadeOutDuration: 0.9,
  repeatDelay: 1.5,
  startDelay: 0.3,
  color: "#9df6ff",
  strokeWidth: 3.5,
  blurPx: 5,
  minDurationScale: 0.92,
  maxDurationScale: 1.18,
  minTravelScale: 0.95,
  maxTravelScale: 1.05,
  peakOpacityScale: 1,
  midOpacityScale: 0.76,
  tailOpacityScale: 0.42,
  pulseWidthScale: 1.75,
};

export const CURRENT_STATUS_GLOW_PATH_PROPS = {
  fill: "none",
  stroke: CURRENT_STATUS_GLOW_CONFIG.color,
  strokeWidth: CURRENT_STATUS_GLOW_CONFIG.strokeWidth,
  strokeLinecap: "round" as const,
  strokeDasharray: "9999 9999",
  strokeDashoffset: "9999",
  style: { filter: `blur(${CURRENT_STATUS_GLOW_CONFIG.blurPx}px)` },
  opacity: "0",
};
